shared:
    image: centos

jobs:
    main:
        steps:
            # To verify if the hyperctl-download script works
            - hyperctl-download: bash -xe scripts/hyperctl-download.sh
            - chmod: chmod +x ./hyperctl
            - test-hyperctl: ./hyperctl info -h
        requires:
            - ~pr
            - ~commit
    publish:
        steps:
            - hyperctl-download: bash -xe scripts/hyperctl-download.sh
            - chmod: chmod +x ./hyperctl
            - test-hyperctl: ./hyperctl info -h
            # Dependencies for the scripts; should make the scripts share steps in the future
            - install-dependencies: yum install -y git wget openssh-clients bzip2
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - tag: ./ci/git-tag.sh
            - release: ./ci/git-release.sh
        environment:
            RELEASE_FILE: hyperctl
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
        requires:
            - main
